fileVersion: 1
id: "5"
mappingDefinitions:
  SOURCE:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
  TRANSFORMATION:
    database: WORK
    schema: WORK_SCHEMA
name: Environment1
type: Environment
